export const SET_DEPENDENCIES = 'SET_DEPENDENCIES';
export const SET_DEPENDENCY = 'SET_DEPENDENCY';
export const ADD_DEPENDENCY = 'ADD_DEPENDENCY';
export const UPDATE_DEPENDENCY = 'UPDATE_DEPENDENCY';
export const REMOVE_DEPENDENCY = 'REMOVE_DEPENDENCY';
export const CLEAR_DEPENDENCY = 'CLEAR_DEPENDENCY';
export const CLEAR_DEPENDENCIES = 'CLEAR_DEPENDENCIES';
